# Generated by Django 3.2.5 on 2021-08-22 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_User_Mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplanner',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_planners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrecipe',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
