# Generated by Django 3.2.5 on 2021-08-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_User_Mgmt', '0002_auto_20210822_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfood',
            old_name='my_user',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='my_user',
            new_name='user_profile',
        ),
    ]
