# Generated by Django 3.2.5 on 2021-08-23 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_User_Mgmt', '0003_auto_20210823_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapp',
            old_name='my_user',
            new_name='user_profile',
        ),
    ]
