# Generated by Django 3.2.5 on 2021-09-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_User_Mgmt', '0004_rename_my_user_userapp_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplanner',
            name='plan_title',
            field=models.CharField(max_length=150),
        ),
    ]
