# Generated by Django 3.2.5 on 2021-08-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_User_Mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_cat', models.CharField(choices=[('res', 'Res'), ('pollo', 'Pollo'), ('cerdo', 'Cerdo'), ('pescado', 'Pescado'), ('huevo', 'Huevo'), ('lacteos', 'Lacteos'), ('frutas', 'Frutas'), ('verduras', 'Verduras'), ('gluten', 'Gluten')], max_length=100)),
                ('ingredient_name', models.CharField(max_length=100, unique=True)),
                ('ingredient_cal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CatalogPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_desc', models.CharField(max_length=50, unique=True)),
                ('moq_value', models.FloatField()),
                ('container_type', models.CharField(choices=[('wrapping', 'Wrapping'), ('container', 'Container'), ('bulk', 'Bulk')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SprmktDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_desc', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitsConvertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equivalency', models.CharField(max_length=50, unique=True)),
                ('unit_value', models.FloatField()),
                ('unit_desc', models.CharField(choices=[('ml', 'mililitros'), ('mg', 'miligramos'), ('l', 'litros'), ('kg', 'kilogramos')], max_length=50)),
                ('unit_type', models.CharField(choices=[('custom', 'Informal'), ('SI', 'Sistema Internacional de Unidades')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SprmktPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spq_value', models.IntegerField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sprmkt_packs', to='App_SprMkt_Mgmt.sprmktdept')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sprmkt_packs', to='App_SprMkt_Mgmt.catalogingredient')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sprmkt_packs', to='App_SprMkt_Mgmt.catalogpackage')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sprmkt_packs', to='App_SprMkt_Mgmt.unitsconvertion')),
            ],
        ),
        migrations.CreateModel(
            name='SprmktList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('inventory', models.BooleanField(default=False)),
                ('purchase', models.BooleanField(default=False)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sprmkt_lists', to='App_User_Mgmt.usermenu')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sprmkt_lists', to='App_SprMkt_Mgmt.sprmktpackaging')),
            ],
        ),
    ]
