# Generated by Django 3.2.5 on 2021-08-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SprMkt_Mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprmktpackaging',
            old_name='dept_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='sprmktpackaging',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='sprmktpackaging',
            old_name='package_id',
            new_name='package_type',
        ),
        migrations.RenameField(
            model_name='sprmktpackaging',
            old_name='unit_id',
            new_name='unit_type',
        ),
    ]
