# Generated by Django 3.2.5 on 2021-08-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SprMkt_Mgmt', '0002_auto_20210822_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitsconvertion',
            name='unit_desc',
            field=models.CharField(choices=[('ml', 'mililitros'), ('gm', 'gramos'), ('l', 'litros'), ('kg', 'kilogramos')], max_length=50),
        ),
    ]
