# Generated by Django 3.2.5 on 2021-08-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SprMkt_Mgmt', '0005_remove_catalogingredient_ingredient_cal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogingredient',
            name='ingredient_cat',
            field=models.CharField(choices=[('res', 'Res'), ('pollo', 'Pollo'), ('cerdo', 'Cerdo'), ('pescado', 'Pescado'), ('huevo', 'Huevo'), ('lacteos', 'Lacteos'), ('frutas', 'Frutas'), ('verduras', 'Verduras'), ('gluten', 'Gluten'), ('cereales y semillas', 'Cereales y Semillas'), ('especias', 'Especias'), ('condimentos', 'Condimentos')], max_length=100),
        ),
    ]
