# Generated by Django 3.2.5 on 2021-08-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SprMkt_Mgmt', '0007_alter_catalogingredient_ingredient_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogingredient',
            name='ingredient_cat',
            field=models.CharField(choices=[('res', 'Res'), ('pollo', 'Pollo'), ('cerdo', 'Cerdo'), ('pescado', 'Pescado'), ('huevo', 'Huevo'), ('lacteos', 'Lacteos'), ('frutas', 'Frutas'), ('verduras', 'Verduras'), ('gluten', 'Gluten'), ('cereales, semillas y leguminosas', 'Cereales, Semillas y Leguminosas'), ('especias, condimentos y salsas', 'Especias, Condimentos y Salsas')], max_length=100),
        ),
    ]
