# Generated by Django 3.2.5 on 2021-08-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SprMkt_Mgmt', '0009_alter_catalogingredient_ingredient_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprmktpackaging',
            name='process_type',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
