# Generated by Django 3.2.5 on 2021-08-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SprMkt_Mgmt', '0010_sprmktpackaging_process_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitsconvertion',
            name='unit_type',
            field=models.CharField(choices=[('user', 'Informal por convención entre usuarios'), ('custom', 'sugerida por al app, bajo revisión'), ('SI', 'Sistema Internacional de Unidades')], max_length=50),
        ),
    ]
