# Generated by Django 3.2.5 on 2021-08-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SprMkt_Mgmt', '0011_alter_unitsconvertion_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogpackage',
            name='container_type',
            field=models.CharField(choices=[('pack', 'Package'), ('container', 'Container'), ('bulk', 'Bulk')], max_length=30),
        ),
    ]
