# Generated by Django 3.2.5 on 2021-08-23 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SprMkt_Mgmt', '0013_rename_process_type_sprmktpackaging_process_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprmktpackaging',
            old_name='process_desc',
            new_name='additional_desc',
        ),
    ]
