# Generated by Django 3.2.5 on 2021-08-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SprMkt_Mgmt', '0014_rename_process_desc_sprmktpackaging_additional_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprmktlist',
            old_name='stock_id',
            new_name='stock_package',
        ),
        migrations.RenameField(
            model_name='sprmktlist',
            old_name='menu_id',
            new_name='user_menu',
        ),
    ]
