# Generated by Django 3.2.5 on 2021-08-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SprMkt_Mgmt', '0015_auto_20210823_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprmktpackaging',
            name='spq_value',
            field=models.FloatField(),
        ),
    ]
