# Generated by Django 3.2.5 on 2021-08-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_User_Mgmt', '0004_rename_my_user_userapp_user_profile'),
        ('App_SprMkt_Mgmt', '0016_alter_sprmktpackaging_spq_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprmktlist',
            name='user_menu',
        ),
        migrations.AddField(
            model_name='sprmktlist',
            name='user_planner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='sprmkt_lists', to='App_User_Mgmt.userplanner'),
            preserve_default=False,
        ),
    ]
