# Generated by Django 3.2.5 on 2021-09-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_User_Mgmt', '0005_alter_userplanner_plan_title'),
        ('App_SprMkt_Mgmt', '0017_auto_20210824_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_qty', models.FloatField()),
                ('unit_desc', models.CharField(choices=[('ml', 'mililitros'), ('gm', 'gramos'), ('l', 'litros'), ('kg', 'kilogramos')], max_length=50)),
                ('check', models.BooleanField(default=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_lists', to='App_SprMkt_Mgmt.catalogingredient')),
                ('user_planner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_lists', to='App_User_Mgmt.userplanner')),
            ],
        ),
    ]
