# Generated by Django 3.2.5 on 2021-08-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('meal_type', models.CharField(choices=[('desayuno', 'Desayuno'), ('brunch', 'Brunch'), ('comida', 'Comida'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=30)),
                ('description', models.TextField()),
                ('n_eats', models.IntegerField()),
                ('time_prep', models.IntegerField()),
                ('level_id', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=30)),
                ('apps_list', models.CharField(choices=[('olla de presion', 'Olla de Presión'), ('licuadora', 'Licuadora'), ('microondas', 'Microondas'), ('horno', 'Horno'), ('procesador', 'Procesador'), ('estufa', 'Estufa')], max_length=30)),
                ('pic_url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apps_name', models.CharField(max_length=30)),
                ('apps_main', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_qty', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc_descrip', models.TextField()),
                ('pic_url', models.CharField(max_length=250)),
                ('cat_recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_procedures', to='App_Recipe_Mgmt.catalogrecipe')),
            ],
        ),
    ]
