# Generated by Django 3.2.5 on 2021-08-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_SprMkt_Mgmt', '0001_initial'),
        ('App_Recipe_Mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='cat_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='App_SprMkt_Mgmt.catalogingredient'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='cat_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='App_Recipe_Mgmt.catalogrecipe'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='App_SprMkt_Mgmt.unitsconvertion'),
        ),
        migrations.AddField(
            model_name='recipeapp',
            name='cat_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_apps', to='App_Recipe_Mgmt.catalogrecipe'),
        ),
        migrations.AddField(
            model_name='catalogrecipe',
            name='recipe_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='App_Recipe_Mgmt.recipecategory'),
        ),
    ]
