# Generated by Django 3.2.5 on 2021-08-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Recipe_Mgmt', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogrecipe',
            old_name='level_id',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='catalogrecipe',
            name='apps_list',
        ),
        migrations.RemoveField(
            model_name='recipeapp',
            name='apps_name',
        ),
        migrations.AddField(
            model_name='recipeapp',
            name='apps_type',
            field=models.CharField(choices=[('olla de presion', 'Olla de Presión'), ('licuadora', 'Licuadora'), ('microondas', 'Microondas'), ('horno', 'Horno'), ('procesador', 'Procesador'), ('estufa', 'Estufa')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
