# Generated by Django 3.2.5 on 2021-08-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Recipe_Mgmt', '0003_auto_20210822_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogrecipe',
            old_name='n_eats',
            new_name='persons',
        ),
    ]
