# Generated by Django 3.2.5 on 2021-08-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Recipe_Mgmt', '0004_rename_n_eats_catalogrecipe_persons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeapp',
            old_name='apps_main',
            new_name='required',
        ),
    ]
